---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: blue-green-simple-vsi-app-pipeline
spec:
  params:
    - name: repository
      description: The Git Repository for the Application Source Code. If empty, the Repository url will be found from toolchain
      default: ""
    - name: branch
      description: The Branch for the Application Source Code
      default: "master"
    - name: revision
      description: The Revision for the Application Source Code
      default: ""
    - name: git-token
      description: access token for the git repo
    - name: region
      description: The IBM Cloud Region in which Virtual Server Instance is running
    - name: api
      description: The IBM Cloud API Endpoint
    - name: apikey
      description: The IBM Cloud API Key
    - name: fail-on-scanned-issues
      description: Force failure of task when vulnerability advisor scan issues are found
      default: "true"
    - name: app-name
      description: The name of the application passed as environment variable
    - name: pipeline-debug
      default: "0"
    - name: commit-timestamp
      description: The Commit Timestamp as set by the Trigger Binding based on the Event Listener invoked. 
    - name: scm-type
      description: The Source Code Management Type as set by the Trigger Binding based on the Event Listener invoked. 
    - name: artifactory
      description: The variable storing artifactory integration with the toolchain
    - name: project-id
    - name: inventory-repo
      description: The variable storing git integration for the repository storing build inventory with the toolchain
    - name: scripts-repo
      description: The variable storing git integration for the repository storing build pipeline code for the toolchain         
    - name: cos-api-key
      description: The API Key to interact with the Cloud Object Storage Instance
    - name: target
      description: The name of the environment where deployment needs to be performed
    - name: cos-bucket-name
      description: The Cloud Object Storage Bucket name where build artifact will be stored.
      default: ""
    - name: insights
      description: The variable storing DevOps Insight integration with the toolchain
    - name: scripts-subpath
      description: The variable storing language scripts-subpath 
    - name: scripts-repo-branch
      description: The branch of the scripts-repo
    - name: inventory-repo-branch
      description: The branch of the inventory-repo
    - name: bastion-host
      description: Bastion Host virtual-server-instance
    - name: bastion-host-user-name
      description: Bastion Host User Name
    - name: bastion-host-ssh-keys
      description: Bastion host 
    - name: blue-pool
      description: Blue Pool for Blue Green Deployemnt
    - name: deployment-strategy
      description: Green Pool for Blue Green Deployemnt
    - name: green-pool
      description: Green Pool for Blue Green Deployemnt
    - name: loadbalancer
      description: Load Balancer Name
    - name: pool-ssh-keys
      description: Blue and Green Pool base64 encoded private SSH key 
    - name: pool-user-name   
      description: Blue and Green Pool User Name
    - name: commons-hosted-region
      default: "https://raw.githubusercontent.com/open-toolchain/commons/master"               
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: git-clone-inventory-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: git-access-token
          value: $(params.git-token)
        - name: repository
          value: $(params.inventory-repo)
        - name: branch
          value: $(params.inventory-repo-branch) 
        - name: revision
          value: $(params.inventory-repo-branch) 
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: git-credentials-json-file
          value: credentials.json
      workspaces:
        - name: output
          workspace: pipeline-ws
          subpath: inventory-repo
    - name: git-clone-scripts-repo
      runAfter: git-clone-inventory-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: repository
          value: $(params.scripts-repo)
        - name: branch
          value: $(params.scripts-repo-branch)
        - name: revision
          value: $(params.scripts-repo-branch)  
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: git-credentials-json-file
          value: credentials.json
      workspaces:
        - name: output
          workspace: pipeline-ws
          subpath: scripts-repo             
    - name: download-artifacts
      taskRef:
        name: download-artifacts
      runAfter: 
        - git-clone-inventory-repo
        - git-clone-scripts-repo  
      params:
        - name: api
          value: $(params.api)
        - name: apikey
          value: $(params.apikey)
        - name: cos-bucket-name
          value: $(params.cos-bucket-name)
        - name: cos-api-key
          value: $(params.cos-api-key)
        - name: artifactory
          value: $(params.artifactory)
        - name: region
          value: $(params.region)          
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: deploy
      taskRef:
        name: deploy
      runAfter: [download-artifacts] 
      params:
        - name: region
          value: $(params.region)
        - name: api
          value: $(params.api)
        - name: apikey
          value: $(params.apikey)
        - name: appname
          value: $(params.app-name)
        - name: artifactory
          value: $(params.artifactory)
        - name: cos-bucket-name
          value: $(params.cos-bucket-name)
        - name: inventory-repo
          value: $(params.inventory-repo)
        - name: objectname
          value: $(tasks.download-artifacts.results.objectname)
        - name: scripts-subpath
          value: $(params.scripts-subpath)
        - name: bastion-host
          value: $(params.bastion-host)
        - name: bastion-host-user-name
          value: $(params.bastion-host-user-name)        
        - name: bastion-host-ssh-keys
          value: $(params.bastion-host-ssh-keys)      
        - name: blue-pool
          value: $(params.blue-pool)          
        - name: deployment-strategy
          value: $(params.deployment-strategy)        
        - name: green-pool
          value: $(params.green-pool)          
        - name: loadbalancer
          value: $(params.loadbalancer)         
        - name: pool-ssh-keys
          value: $(params.pool-ssh-keys)         
        - name: pool-user-name   
          value: $(params.pool-user-name)
        - name: commons-hosted-region
          value: $(params.commons-hosted-region)                                
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: acceptance-test
      taskRef:
        name: acceptance-test
      runAfter: [ deploy ]
      params:
        - name: region
          value: $(params.region)
        - name: api
          value: $(params.api)
        - name: apikey
          value: $(params.apikey)      
        - name: inventory-repo
          value: $(params.inventory-repo)
        - name: scripts-subpath
          value: $(params.scripts-subpath)
        - name: bastion-host
          value: $(params.bastion-host)
        - name: bastion-host-user-name
          value: $(params.bastion-host-user-name)        
        - name: bastion-host-ssh-keys
          value: $(params.bastion-host-ssh-keys)      
        - name: blue-pool
          value: $(params.blue-pool)          
        - name: deployment-strategy
          value: $(params.deployment-strategy)        
        - name: green-pool
          value: $(params.green-pool)          
        - name: loadbalancer
          value: $(params.loadbalancer)         
        - name: pool-ssh-keys
          value: $(params.pool-ssh-keys)         
        - name: pool-user-name   
          value: $(params.pool-user-name)                       
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: release
      taskRef:
        name: release
      runAfter: [ acceptance-test ]     
      params:
        - name: region
          value: $(params.region)
        - name: api
          value: $(params.api)
        - name: apikey
          value: $(params.apikey)      
        - name: scripts-subpath
          value: $(params.scripts-subpath)     
        - name: blue-pool
          value: $(params.blue-pool)                 
        - name: green-pool
          value: $(params.green-pool)          
        - name: loadbalancer
          value: $(params.loadbalancer)
        - name: deployment-strategy
          value: $(params.deployment-strategy)
        - name: commons-hosted-region
          value: $(params.commons-hosted-region)                                                   
      workspaces:
        - name: output
          workspace: pipeline-ws                    
    - name: publish-doi-deployrecord
      taskRef:
        name: publish-doi-deployrecord
      runAfter: [acceptance-test]
      when:
        - input: $(params.insights)
          operator: in
          values: ["draservicebroker"]
      params:
        - name: api
          value: $(params.api)
        - name: apikey
          value: $(params.apikey)
        - name: appname
          value: $(params.app-name)
        - name: inventory-repo
          value: $(params.inventory-repo)
        - name: target
          value: $(params.target)
        - name: build_number
          value: $(tasks.download-artifacts.results.build_number)
      workspaces:
        - name: output
          workspace: pipeline-ws
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: blue-green-switch-pipeline
spec:
  params:
    - name: region
      description: The IBM Cloud Region in which Virtual Server Instance is running
    - name: api
      description: The IBM Cloud API Endpoint
    - name: apikey
      description: The IBM Cloud API Key  
    - name: scripts-subpath
      description: The variable storing language scripts-subpath 
    - name: fail-on-scanned-issues
      description: Force failure of task when vulnerability advisor scan issues are found
      default: "true"
    - name: pipeline-debug
      default: "0"
    - name: blue-pool
      description: Blue Pool for Blue Green Deployemnt
    - name: deployment-strategy
      description: Green Pool for Blue Green Deployemnt
    - name: green-pool
      description: Green Pool for Blue Green Deployemnt
    - name: loadbalancer
      description: Load Balancer Name
    - name: commons-hosted-region
      default: "https://raw.githubusercontent.com/open-toolchain/commons/master"               
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: blue-green-switch
      taskRef:
        name: release     
      params:
        - name: region
          value: $(params.region)
        - name: api
          value: $(params.api)
        - name: apikey
          value: $(params.apikey)      
        - name: scripts-subpath
          value: $(params.scripts-subpath)     
        - name: blue-pool
          value: $(params.blue-pool)                 
        - name: green-pool
          value: $(params.green-pool)          
        - name: loadbalancer
          value: $(params.loadbalancer)
        - name: deployment-strategy
          value: $(params.deployment-strategy)
        - name: commons-hosted-region
          value: $(params.commons-hosted-region)                                                    
      workspaces:
        - name: output
          workspace: pipeline-ws